### ISSUE TITLE
Preambulo

### ISSUE THREAD

**Issue by GYOVANNE** [josaiasmoura/ufersatex2#1]
Oi Josaias, tudo bem? Parabéns pela iniciativa. Estou utilizando seu projeto para meu TCC. Gostaria de contribuir informando que para editar utilizando o editor online OverLeaf foi preciso retirar o \input{lib/preambulo} do documento.tex e inserir todo o conteúdo do preambulo no próprio documento.tex. De alguma maneira o OverLeaf não compila se a lista de pacotes e outros não estiver no documento principal. Como sugestão, pode adicionar essa observação no README do repositório para ajudar a galera que usa OverLeaf. Valeu e Obrigado!!!!

**Comment by josaiasmoura** [comment]
Olá @GYOVANNE, tudo sim e contigo? 
Eu não tinha testado no OverLeaf ainda, usei sempre compiladores locais (Windows e Linux). Muito obrigado por reportar o bug, vou tentar reproduzir ele aqui. Obrigado também pela sugestão, se quiser pode alterar você mesmo o README e enviar um PR ;)
